apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapp-review
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: vjkancherla
        
        # The Github repository
        repo: Example-K8s-Applications
       
        # Reference to a Secret containing an access token. (optional)
        tokenRef:
          secretName: github-token
          key: token
        
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
          - preview
      
      #polls every requeueAfterSeconds interval (defaulting to every 30 minutes) to detect changes
      requeueAfterSeconds: 90
  template:
    metadata:
      name: 'webapp-{{branch}}-{{head_short_sha}}-pr{{number}}'
      namespace: argocd
    spec:
      source:
        repoURL: 'https://github.com/vjkancherla/Example-K8s-Applications.git'
        targetRevision: '{{head_sha}}'
        path: a-webapp/helm/webapp
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: webapp-{{branch}}-{{head_short_sha}}-pr{{number}}
      syncPolicy:
        automated: {}
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true