apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-review
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: webapp-live
  project: default
  source:
    repoURL: 'https://github.com/vjkancherla/Example-K8s-Applications.git'
    path: a-webapp/helm/webapp
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true